// API Service - Replace mock data with real API calls when ready
// TODO: Replace BASE_URL with your actual API endpoint
// const BASE_URL = "https://your-api.example.com";

import type { Tool, ToolDetail } from "@/types/api";

// =============================================================================
// MOCK DATA - 50 LLMs + 50 AI Tools
// =============================================================================

const mockTools: Tool[] = [
  // ===== LLMs (50) =====
  {
    id: "gpt-4o",
    rank: 1,
    name: "GPT-4o",
    company: "OpenAI",
    logo: "https://logo.clearbit.com/openai.com",
    sentiment: { positive: 78, neutral: 17, negative: 5 },
    mentions: 89420,
    trend: "up",
    trendPercent7d: 12,
    sparklineData: [72, 75, 78, 80, 82, 85, 89],
    type: "llm",
  },
  {
    id: "gpt-4-turbo",
    rank: 2,
    name: "GPT-4 Turbo",
    company: "OpenAI",
    logo: "https://logo.clearbit.com/openai.com",
    sentiment: { positive: 74, neutral: 20, negative: 6 },
    mentions: 67300,
    trend: "stable",
    trendPercent7d: 2,
    sparklineData: [65, 66, 65, 67, 66, 67, 67],
    type: "llm",
  },
  {
    id: "gpt-5",
    rank: 3,
    name: "GPT-5",
    company: "OpenAI",
    logo: "https://logo.clearbit.com/openai.com",
    sentiment: { positive: 82, neutral: 14, negative: 4 },
    mentions: 124500,
    trend: "up",
    trendPercent7d: 45,
    sparklineData: [45, 58, 72, 89, 102, 115, 124],
    type: "llm",
  },
  {
    id: "gpt-5-2",
    rank: 4,
    name: "GPT-5.2",
    company: "OpenAI",
    logo: "https://logo.clearbit.com/openai.com",
    sentiment: { positive: 85, neutral: 12, negative: 3 },
    mentions: 98700,
    trend: "up",
    trendPercent7d: 67,
    sparklineData: [32, 45, 58, 72, 85, 92, 98],
    type: "llm",
  },
  {
    id: "claude-3-opus",
    rank: 5,
    name: "Claude 3 Opus",
    company: "Anthropic",
    logo: "https://logo.clearbit.com/anthropic.com",
    sentiment: { positive: 81, neutral: 15, negative: 4 },
    mentions: 54200,
    trend: "stable",
    trendPercent7d: -2,
    sparklineData: [55, 54, 55, 54, 53, 54, 54],
    type: "llm",
  },
  {
    id: "claude-3-5-sonnet",
    rank: 6,
    name: "Claude 3.5 Sonnet",
    company: "Anthropic",
    logo: "https://logo.clearbit.com/anthropic.com",
    sentiment: { positive: 84, neutral: 13, negative: 3 },
    mentions: 72800,
    trend: "up",
    trendPercent7d: 18,
    sparklineData: [58, 62, 65, 68, 70, 72, 73],
    type: "llm",
  },
  {
    id: "claude-4",
    rank: 7,
    name: "Claude 4",
    company: "Anthropic",
    logo: "https://logo.clearbit.com/anthropic.com",
    sentiment: { positive: 88, neutral: 10, negative: 2 },
    mentions: 112300,
    trend: "up",
    trendPercent7d: 52,
    sparklineData: [48, 62, 75, 88, 98, 106, 112],
    type: "llm",
  },
  {
    id: "claude-4-5",
    rank: 8,
    name: "Claude 4.5",
    company: "Anthropic",
    logo: "https://logo.clearbit.com/anthropic.com",
    sentiment: { positive: 89, neutral: 9, negative: 2 },
    mentions: 87600,
    trend: "up",
    trendPercent7d: 78,
    sparklineData: [28, 42, 55, 68, 76, 82, 88],
    type: "llm",
  },
  {
    id: "gemini-1-5-pro",
    rank: 9,
    name: "Gemini 1.5 Pro",
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    sentiment: { positive: 72, neutral: 22, negative: 6 },
    mentions: 48900,
    trend: "down",
    trendPercent7d: -8,
    sparklineData: [54, 52, 51, 50, 49, 49, 49],
    type: "llm",
  },
  {
    id: "gemini-2-0-flash",
    rank: 10,
    name: "Gemini 2.0 Flash",
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    sentiment: { positive: 76, neutral: 19, negative: 5 },
    mentions: 62400,
    trend: "up",
    trendPercent7d: 15,
    sparklineData: [52, 54, 56, 58, 60, 61, 62],
    type: "llm",
  },
  {
    id: "gemini-2-5-pro",
    rank: 11,
    name: "Gemini 2.5 Pro",
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    sentiment: { positive: 79, neutral: 17, negative: 4 },
    mentions: 78300,
    trend: "up",
    trendPercent7d: 28,
    sparklineData: [55, 60, 65, 70, 74, 76, 78],
    type: "llm",
  },
  {
    id: "gemini-3-pro",
    rank: 12,
    name: "Gemini 3 Pro",
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    sentiment: { positive: 83, neutral: 14, negative: 3 },
    mentions: 95200,
    trend: "up",
    trendPercent7d: 42,
    sparklineData: [48, 58, 68, 78, 86, 91, 95],
    type: "llm",
  },
  {
    id: "gemini-3-flash",
    rank: 13,
    name: "Gemini 3 Flash",
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    sentiment: { positive: 77, neutral: 18, negative: 5 },
    mentions: 58700,
    trend: "up",
    trendPercent7d: 22,
    sparklineData: [45, 48, 51, 54, 56, 57, 59],
    type: "llm",
  },
  {
    id: "llama-3",
    rank: 14,
    name: "Llama 3",
    company: "Meta",
    logo: "https://logo.clearbit.com/meta.com",
    sentiment: { positive: 75, neutral: 20, negative: 5 },
    mentions: 42100,
    trend: "stable",
    trendPercent7d: 1,
    sparklineData: [42, 42, 41, 42, 42, 42, 42],
    type: "llm",
  },
  {
    id: "llama-4-maverick",
    rank: 15,
    name: "Llama 4 Maverick",
    company: "Meta",
    logo: "https://logo.clearbit.com/meta.com",
    sentiment: { positive: 80, neutral: 16, negative: 4 },
    mentions: 68400,
    trend: "up",
    trendPercent7d: 35,
    sparklineData: [42, 48, 54, 60, 64, 66, 68],
    type: "llm",
  },
  {
    id: "llama-4-scout",
    rank: 16,
    name: "Llama 4 Scout",
    company: "Meta",
    logo: "https://logo.clearbit.com/meta.com",
    sentiment: { positive: 78, neutral: 18, negative: 4 },
    mentions: 52300,
    trend: "up",
    trendPercent7d: 25,
    sparklineData: [38, 42, 45, 48, 50, 51, 52],
    type: "llm",
  },
  {
    id: "mistral-large",
    rank: 17,
    name: "Mistral Large",
    company: "Mistral AI",
    logo: "https://logo.clearbit.com/mistral.ai",
    sentiment: { positive: 76, neutral: 19, negative: 5 },
    mentions: 38600,
    trend: "up",
    trendPercent7d: 12,
    sparklineData: [32, 34, 35, 36, 37, 38, 39],
    type: "llm",
  },
  {
    id: "mistral-medium",
    rank: 18,
    name: "Mistral Medium",
    company: "Mistral AI",
    logo: "https://logo.clearbit.com/mistral.ai",
    sentiment: { positive: 72, neutral: 22, negative: 6 },
    mentions: 28400,
    trend: "stable",
    trendPercent7d: -1,
    sparklineData: [29, 29, 28, 28, 28, 28, 28],
    type: "llm",
  },
  {
    id: "mixtral-8x7b",
    rank: 19,
    name: "Mixtral 8x7B",
    company: "Mistral AI",
    logo: "https://logo.clearbit.com/mistral.ai",
    sentiment: { positive: 74, neutral: 20, negative: 6 },
    mentions: 32100,
    trend: "down",
    trendPercent7d: -5,
    sparklineData: [35, 34, 34, 33, 33, 32, 32],
    type: "llm",
  },
  {
    id: "mixtral-8x22b",
    rank: 20,
    name: "Mixtral 8x22B",
    company: "Mistral AI",
    logo: "https://logo.clearbit.com/mistral.ai",
    sentiment: { positive: 77, neutral: 18, negative: 5 },
    mentions: 35800,
    trend: "up",
    trendPercent7d: 8,
    sparklineData: [32, 33, 34, 34, 35, 35, 36],
    type: "llm",
  },
  {
    id: "deepseek-v3",
    rank: 21,
    name: "DeepSeek V3",
    company: "DeepSeek",
    logo: "https://logo.clearbit.com/deepseek.com",
    sentiment: { positive: 79, neutral: 17, negative: 4 },
    mentions: 45600,
    trend: "up",
    trendPercent7d: 32,
    sparklineData: [28, 32, 36, 40, 43, 45, 46],
    type: "llm",
  },
  {
    id: "deepseek-v4",
    rank: 22,
    name: "DeepSeek V4",
    company: "DeepSeek",
    logo: "https://logo.clearbit.com/deepseek.com",
    sentiment: { positive: 82, neutral: 15, negative: 3 },
    mentions: 67800,
    trend: "up",
    trendPercent7d: 58,
    sparklineData: [32, 42, 50, 56, 62, 65, 68],
    type: "llm",
  },
  {
    id: "deepseek-coder",
    rank: 23,
    name: "DeepSeek Coder",
    company: "DeepSeek",
    logo: "https://logo.clearbit.com/deepseek.com",
    sentiment: { positive: 81, neutral: 16, negative: 3 },
    mentions: 38200,
    trend: "up",
    trendPercent7d: 18,
    sparklineData: [30, 32, 34, 35, 36, 37, 38],
    type: "llm",
  },
  {
    id: "grok-3",
    rank: 24,
    name: "Grok 3",
    company: "xAI",
    logo: "https://logo.clearbit.com/x.ai",
    sentiment: { positive: 71, neutral: 21, negative: 8 },
    mentions: 52400,
    trend: "up",
    trendPercent7d: 15,
    sparklineData: [42, 44, 46, 48, 50, 51, 52],
    type: "llm",
  },
  {
    id: "grok-4",
    rank: 25,
    name: "Grok 4",
    company: "xAI",
    logo: "https://logo.clearbit.com/x.ai",
    sentiment: { positive: 74, neutral: 19, negative: 7 },
    mentions: 78900,
    trend: "up",
    trendPercent7d: 48,
    sparklineData: [42, 52, 60, 68, 74, 77, 79],
    type: "llm",
  },
  {
    id: "command-r-plus",
    rank: 26,
    name: "Command R+",
    company: "Cohere",
    logo: "https://logo.clearbit.com/cohere.com",
    sentiment: { positive: 73, neutral: 22, negative: 5 },
    mentions: 24600,
    trend: "stable",
    trendPercent7d: 3,
    sparklineData: [23, 24, 24, 24, 24, 25, 25],
    type: "llm",
  },
  {
    id: "command-r",
    rank: 27,
    name: "Command R",
    company: "Cohere",
    logo: "https://logo.clearbit.com/cohere.com",
    sentiment: { positive: 70, neutral: 24, negative: 6 },
    mentions: 18900,
    trend: "down",
    trendPercent7d: -4,
    sparklineData: [20, 20, 19, 19, 19, 19, 19],
    type: "llm",
  },
  {
    id: "perplexity-online",
    rank: 28,
    name: "Perplexity Online",
    company: "Perplexity AI",
    logo: "https://logo.clearbit.com/perplexity.ai",
    sentiment: { positive: 78, neutral: 18, negative: 4 },
    mentions: 56700,
    trend: "up",
    trendPercent7d: 22,
    sparklineData: [42, 46, 49, 52, 54, 55, 57],
    type: "llm",
  },
  {
    id: "qwen-2-5",
    rank: 29,
    name: "Qwen 2.5",
    company: "Alibaba",
    logo: "https://logo.clearbit.com/alibaba.com",
    sentiment: { positive: 75, neutral: 20, negative: 5 },
    mentions: 32400,
    trend: "up",
    trendPercent7d: 14,
    sparklineData: [26, 28, 29, 30, 31, 32, 32],
    type: "llm",
  },
  {
    id: "qwen-2",
    rank: 30,
    name: "Qwen 2",
    company: "Alibaba",
    logo: "https://logo.clearbit.com/alibaba.com",
    sentiment: { positive: 72, neutral: 22, negative: 6 },
    mentions: 24100,
    trend: "down",
    trendPercent7d: -6,
    sparklineData: [26, 26, 25, 25, 24, 24, 24],
    type: "llm",
  },
  {
    id: "yi-large",
    rank: 31,
    name: "Yi-Large",
    company: "01.AI",
    logo: "https://logo.clearbit.com/01.ai",
    sentiment: { positive: 74, neutral: 21, negative: 5 },
    mentions: 18600,
    trend: "stable",
    trendPercent7d: 2,
    sparklineData: [18, 18, 18, 18, 19, 19, 19],
    type: "llm",
  },
  {
    id: "gemma-2",
    rank: 32,
    name: "Gemma 2",
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    sentiment: { positive: 73, neutral: 22, negative: 5 },
    mentions: 28700,
    trend: "stable",
    trendPercent7d: -1,
    sparklineData: [29, 29, 29, 29, 28, 29, 29],
    type: "llm",
  },
  {
    id: "gemma-3",
    rank: 33,
    name: "Gemma 3",
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    sentiment: { positive: 76, neutral: 19, negative: 5 },
    mentions: 35200,
    trend: "up",
    trendPercent7d: 18,
    sparklineData: [28, 30, 31, 33, 34, 35, 35],
    type: "llm",
  },
  {
    id: "phi-3",
    rank: 34,
    name: "Phi-3",
    company: "Microsoft",
    logo: "https://logo.clearbit.com/microsoft.com",
    sentiment: { positive: 74, neutral: 21, negative: 5 },
    mentions: 22400,
    trend: "stable",
    trendPercent7d: 1,
    sparklineData: [22, 22, 22, 22, 22, 22, 22],
    type: "llm",
  },
  {
    id: "phi-4",
    rank: 35,
    name: "Phi-4",
    company: "Microsoft",
    logo: "https://logo.clearbit.com/microsoft.com",
    sentiment: { positive: 78, neutral: 18, negative: 4 },
    mentions: 38900,
    trend: "up",
    trendPercent7d: 28,
    sparklineData: [28, 30, 33, 35, 37, 38, 39],
    type: "llm",
  },
  {
    id: "dbrx",
    rank: 36,
    name: "DBRX",
    company: "Databricks",
    logo: "https://logo.clearbit.com/databricks.com",
    sentiment: { positive: 71, neutral: 23, negative: 6 },
    mentions: 14800,
    trend: "stable",
    trendPercent7d: 0,
    sparklineData: [15, 15, 15, 15, 15, 15, 15],
    type: "llm",
  },
  {
    id: "falcon-180b",
    rank: 37,
    name: "Falcon 180B",
    company: "TII",
    logo: "https://logo.clearbit.com/tii.ae",
    sentiment: { positive: 69, neutral: 24, negative: 7 },
    mentions: 12300,
    trend: "down",
    trendPercent7d: -8,
    sparklineData: [14, 13, 13, 13, 12, 12, 12],
    type: "llm",
  },
  {
    id: "inflection-pi",
    rank: 38,
    name: "Inflection Pi",
    company: "Inflection AI",
    logo: "https://logo.clearbit.com/inflection.ai",
    sentiment: { positive: 72, neutral: 22, negative: 6 },
    mentions: 16400,
    trend: "stable",
    trendPercent7d: -2,
    sparklineData: [17, 17, 17, 16, 16, 16, 16],
    type: "llm",
  },
  {
    id: "kimi-k2",
    rank: 39,
    name: "Kimi K2",
    company: "Moonshot AI",
    logo: "https://logo.clearbit.com/moonshot.cn",
    sentiment: { positive: 76, neutral: 19, negative: 5 },
    mentions: 28900,
    trend: "up",
    trendPercent7d: 25,
    sparklineData: [20, 22, 24, 26, 27, 28, 29],
    type: "llm",
  },
  {
    id: "claude-3-haiku",
    rank: 40,
    name: "Claude 3 Haiku",
    company: "Anthropic",
    logo: "https://logo.clearbit.com/anthropic.com",
    sentiment: { positive: 77, neutral: 19, negative: 4 },
    mentions: 34200,
    trend: "stable",
    trendPercent7d: -1,
    sparklineData: [35, 35, 34, 34, 34, 34, 34],
    type: "llm",
  },
  {
    id: "claude-3-sonnet",
    rank: 41,
    name: "Claude 3 Sonnet",
    company: "Anthropic",
    logo: "https://logo.clearbit.com/anthropic.com",
    sentiment: { positive: 79, neutral: 17, negative: 4 },
    mentions: 42600,
    trend: "down",
    trendPercent7d: -5,
    sparklineData: [46, 45, 44, 44, 43, 43, 43],
    type: "llm",
  },
  {
    id: "gpt-4o-mini",
    rank: 42,
    name: "GPT-4o Mini",
    company: "OpenAI",
    logo: "https://logo.clearbit.com/openai.com",
    sentiment: { positive: 76, neutral: 19, negative: 5 },
    mentions: 48700,
    trend: "up",
    trendPercent7d: 8,
    sparklineData: [44, 45, 46, 47, 48, 48, 49],
    type: "llm",
  },
  {
    id: "gemini-nano",
    rank: 43,
    name: "Gemini Nano",
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    sentiment: { positive: 71, neutral: 23, negative: 6 },
    mentions: 18200,
    trend: "stable",
    trendPercent7d: 2,
    sparklineData: [17, 18, 18, 18, 18, 18, 18],
    type: "llm",
  },
  {
    id: "llama-3-1-405b",
    rank: 44,
    name: "Llama 3.1 405B",
    company: "Meta",
    logo: "https://logo.clearbit.com/meta.com",
    sentiment: { positive: 78, neutral: 18, negative: 4 },
    mentions: 36400,
    trend: "stable",
    trendPercent7d: -2,
    sparklineData: [38, 37, 37, 37, 36, 36, 36],
    type: "llm",
  },
  {
    id: "codestral",
    rank: 45,
    name: "Codestral",
    company: "Mistral AI",
    logo: "https://logo.clearbit.com/mistral.ai",
    sentiment: { positive: 80, neutral: 16, negative: 4 },
    mentions: 28600,
    trend: "up",
    trendPercent7d: 15,
    sparklineData: [24, 25, 26, 27, 28, 28, 29],
    type: "llm",
  },
  {
    id: "starcoder-2",
    rank: 46,
    name: "StarCoder 2",
    company: "BigCode",
    logo: "https://logo.clearbit.com/huggingface.co",
    sentiment: { positive: 74, neutral: 21, negative: 5 },
    mentions: 16800,
    trend: "stable",
    trendPercent7d: 1,
    sparklineData: [17, 17, 17, 17, 17, 17, 17],
    type: "llm",
  },
  {
    id: "wizardcoder",
    rank: 47,
    name: "WizardCoder",
    company: "WizardLM",
    logo: "https://logo.clearbit.com/github.com",
    sentiment: { positive: 72, neutral: 22, negative: 6 },
    mentions: 12400,
    trend: "down",
    trendPercent7d: -6,
    sparklineData: [14, 13, 13, 13, 12, 12, 12],
    type: "llm",
  },
  {
    id: "sonar",
    rank: 48,
    name: "Sonar",
    company: "Perplexity AI",
    logo: "https://logo.clearbit.com/perplexity.ai",
    sentiment: { positive: 76, neutral: 19, negative: 5 },
    mentions: 24800,
    trend: "up",
    trendPercent7d: 12,
    sparklineData: [21, 22, 23, 23, 24, 24, 25],
    type: "llm",
  },
  {
    id: "openai-o1",
    rank: 49,
    name: "OpenAI o1",
    company: "OpenAI",
    logo: "https://logo.clearbit.com/openai.com",
    sentiment: { positive: 81, neutral: 15, negative: 4 },
    mentions: 58400,
    trend: "up",
    trendPercent7d: 18,
    sparklineData: [48, 50, 52, 54, 56, 57, 58],
    type: "llm",
  },
  {
    id: "openai-o3",
    rank: 50,
    name: "OpenAI o3",
    company: "OpenAI",
    logo: "https://logo.clearbit.com/openai.com",
    sentiment: { positive: 84, neutral: 13, negative: 3 },
    mentions: 72600,
    trend: "up",
    trendPercent7d: 35,
    sparklineData: [48, 54, 60, 65, 69, 71, 73],
    type: "llm",
  },

  // ===== AI TOOLS (50) =====
  {
    id: "cursor",
    rank: 1,
    name: "Cursor",
    company: "Cursor Inc.",
    logo: "https://logo.clearbit.com/cursor.com",
    sentiment: { positive: 87, neutral: 10, negative: 3 },
    mentions: 68400,
    trend: "up",
    trendPercent7d: 32,
    sparklineData: [48, 52, 56, 60, 64, 66, 68],
    type: "tool",
  },
  {
    id: "lovable",
    rank: 2,
    name: "Lovable",
    company: "Lovable",
    logo: "https://logo.clearbit.com/lovable.dev",
    sentiment: { positive: 89, neutral: 9, negative: 2 },
    mentions: 52800,
    trend: "up",
    trendPercent7d: 45,
    sparklineData: [32, 38, 42, 46, 49, 51, 53],
    type: "tool",
  },
  {
    id: "v0",
    rank: 3,
    name: "v0",
    company: "Vercel",
    logo: "https://logo.clearbit.com/vercel.com",
    sentiment: { positive: 82, neutral: 14, negative: 4 },
    mentions: 45600,
    trend: "up",
    trendPercent7d: 28,
    sparklineData: [32, 35, 38, 41, 43, 44, 46],
    type: "tool",
  },
  {
    id: "bolt-new",
    rank: 4,
    name: "Bolt.new",
    company: "StackBlitz",
    logo: "https://logo.clearbit.com/stackblitz.com",
    sentiment: { positive: 84, neutral: 12, negative: 4 },
    mentions: 38900,
    trend: "up",
    trendPercent7d: 38,
    sparklineData: [24, 28, 31, 34, 36, 38, 39],
    type: "tool",
  },
  {
    id: "replit",
    rank: 5,
    name: "Replit",
    company: "Replit",
    logo: "https://logo.clearbit.com/replit.com",
    sentiment: { positive: 76, neutral: 18, negative: 6 },
    mentions: 42300,
    trend: "up",
    trendPercent7d: 12,
    sparklineData: [36, 38, 39, 40, 41, 42, 42],
    type: "tool",
  },
  {
    id: "github-copilot",
    rank: 6,
    name: "GitHub Copilot",
    company: "GitHub",
    logo: "https://logo.clearbit.com/github.com",
    sentiment: { positive: 78, neutral: 17, negative: 5 },
    mentions: 72400,
    trend: "stable",
    trendPercent7d: 3,
    sparklineData: [70, 71, 71, 72, 72, 72, 72],
    type: "tool",
  },
  {
    id: "windsurf",
    rank: 7,
    name: "Windsurf",
    company: "Codeium",
    logo: "https://logo.clearbit.com/codeium.com",
    sentiment: { positive: 83, neutral: 13, negative: 4 },
    mentions: 36700,
    trend: "up",
    trendPercent7d: 42,
    sparklineData: [22, 26, 29, 32, 34, 35, 37],
    type: "tool",
  },
  {
    id: "chatgpt-app",
    rank: 8,
    name: "ChatGPT",
    company: "OpenAI",
    logo: "https://logo.clearbit.com/openai.com",
    sentiment: { positive: 75, neutral: 19, negative: 6 },
    mentions: 124500,
    trend: "up",
    trendPercent7d: 8,
    sparklineData: [112, 115, 118, 120, 122, 123, 125],
    type: "tool",
  },
  {
    id: "claude-ai",
    rank: 9,
    name: "Claude.ai",
    company: "Anthropic",
    logo: "https://logo.clearbit.com/anthropic.com",
    sentiment: { positive: 82, neutral: 14, negative: 4 },
    mentions: 68900,
    trend: "up",
    trendPercent7d: 18,
    sparklineData: [56, 58, 61, 64, 66, 68, 69],
    type: "tool",
  },
  {
    id: "perplexity-app",
    rank: 10,
    name: "Perplexity",
    company: "Perplexity AI",
    logo: "https://logo.clearbit.com/perplexity.ai",
    sentiment: { positive: 80, neutral: 16, negative: 4 },
    mentions: 58400,
    trend: "up",
    trendPercent7d: 22,
    sparklineData: [45, 48, 51, 54, 56, 57, 58],
    type: "tool",
  },
  {
    id: "midjourney",
    rank: 11,
    name: "Midjourney",
    company: "Midjourney",
    logo: "https://logo.clearbit.com/midjourney.com",
    sentiment: { positive: 84, neutral: 12, negative: 4 },
    mentions: 86200,
    trend: "stable",
    trendPercent7d: -2,
    sparklineData: [88, 88, 87, 87, 86, 86, 86],
    type: "tool",
  },
  {
    id: "dall-e-3",
    rank: 12,
    name: "DALL-E 3",
    company: "OpenAI",
    logo: "https://logo.clearbit.com/openai.com",
    sentiment: { positive: 79, neutral: 16, negative: 5 },
    mentions: 52600,
    trend: "stable",
    trendPercent7d: 1,
    sparklineData: [52, 52, 52, 52, 53, 53, 53],
    type: "tool",
  },
  {
    id: "stable-diffusion",
    rank: 13,
    name: "Stable Diffusion",
    company: "Stability AI",
    logo: "https://logo.clearbit.com/stability.ai",
    sentiment: { positive: 76, neutral: 18, negative: 6 },
    mentions: 48900,
    trend: "down",
    trendPercent7d: -5,
    sparklineData: [52, 51, 51, 50, 49, 49, 49],
    type: "tool",
  },
  {
    id: "runway",
    rank: 14,
    name: "Runway",
    company: "Runway",
    logo: "https://logo.clearbit.com/runwayml.com",
    sentiment: { positive: 81, neutral: 15, negative: 4 },
    mentions: 42300,
    trend: "up",
    trendPercent7d: 18,
    sparklineData: [34, 36, 38, 40, 41, 42, 42],
    type: "tool",
  },
  {
    id: "figma-ai",
    rank: 15,
    name: "Figma AI",
    company: "Figma",
    logo: "https://logo.clearbit.com/figma.com",
    sentiment: { positive: 77, neutral: 18, negative: 5 },
    mentions: 36800,
    trend: "up",
    trendPercent7d: 25,
    sparklineData: [28, 30, 32, 34, 35, 36, 37],
    type: "tool",
  },
  {
    id: "notion-ai",
    rank: 16,
    name: "Notion AI",
    company: "Notion",
    logo: "https://logo.clearbit.com/notion.so",
    sentiment: { positive: 78, neutral: 17, negative: 5 },
    mentions: 44200,
    trend: "up",
    trendPercent7d: 12,
    sparklineData: [38, 40, 41, 42, 43, 44, 44],
    type: "tool",
  },
  {
    id: "jasper",
    rank: 17,
    name: "Jasper",
    company: "Jasper AI",
    logo: "https://logo.clearbit.com/jasper.ai",
    sentiment: { positive: 72, neutral: 21, negative: 7 },
    mentions: 28400,
    trend: "down",
    trendPercent7d: -8,
    sparklineData: [32, 31, 30, 29, 29, 28, 28],
    type: "tool",
  },
  {
    id: "copy-ai",
    rank: 18,
    name: "Copy.ai",
    company: "Copy.ai",
    logo: "https://logo.clearbit.com/copy.ai",
    sentiment: { positive: 71, neutral: 22, negative: 7 },
    mentions: 22600,
    trend: "stable",
    trendPercent7d: -2,
    sparklineData: [23, 23, 23, 23, 22, 23, 23],
    type: "tool",
  },
  {
    id: "grammarly-ai",
    rank: 19,
    name: "Grammarly AI",
    company: "Grammarly",
    logo: "https://logo.clearbit.com/grammarly.com",
    sentiment: { positive: 76, neutral: 19, negative: 5 },
    mentions: 38900,
    trend: "stable",
    trendPercent7d: 2,
    sparklineData: [38, 38, 38, 39, 39, 39, 39],
    type: "tool",
  },
  {
    id: "deepl-write",
    rank: 20,
    name: "DeepL Write",
    company: "DeepL",
    logo: "https://logo.clearbit.com/deepl.com",
    sentiment: { positive: 79, neutral: 17, negative: 4 },
    mentions: 32400,
    trend: "up",
    trendPercent7d: 10,
    sparklineData: [28, 29, 30, 31, 31, 32, 32],
    type: "tool",
  },
  {
    id: "otter-ai",
    rank: 21,
    name: "Otter.ai",
    company: "Otter.ai",
    logo: "https://logo.clearbit.com/otter.ai",
    sentiment: { positive: 77, neutral: 18, negative: 5 },
    mentions: 26800,
    trend: "up",
    trendPercent7d: 8,
    sparklineData: [24, 25, 25, 26, 26, 27, 27],
    type: "tool",
  },
  {
    id: "descript",
    rank: 22,
    name: "Descript",
    company: "Descript",
    logo: "https://logo.clearbit.com/descript.com",
    sentiment: { positive: 80, neutral: 16, negative: 4 },
    mentions: 28600,
    trend: "up",
    trendPercent7d: 12,
    sparklineData: [24, 25, 26, 27, 28, 28, 29],
    type: "tool",
  },
  {
    id: "elevenlabs",
    rank: 23,
    name: "ElevenLabs",
    company: "ElevenLabs",
    logo: "https://logo.clearbit.com/elevenlabs.io",
    sentiment: { positive: 83, neutral: 13, negative: 4 },
    mentions: 48200,
    trend: "up",
    trendPercent7d: 28,
    sparklineData: [35, 38, 41, 44, 46, 47, 48],
    type: "tool",
  },
  {
    id: "synthesia",
    rank: 24,
    name: "Synthesia",
    company: "Synthesia",
    logo: "https://logo.clearbit.com/synthesia.io",
    sentiment: { positive: 78, neutral: 17, negative: 5 },
    mentions: 32400,
    trend: "up",
    trendPercent7d: 15,
    sparklineData: [26, 28, 29, 30, 31, 32, 32],
    type: "tool",
  },
  {
    id: "heygen",
    rank: 25,
    name: "HeyGen",
    company: "HeyGen",
    logo: "https://logo.clearbit.com/heygen.com",
    sentiment: { positive: 79, neutral: 16, negative: 5 },
    mentions: 36800,
    trend: "up",
    trendPercent7d: 22,
    sparklineData: [28, 30, 32, 34, 35, 36, 37],
    type: "tool",
  },
  {
    id: "canva-ai",
    rank: 26,
    name: "Canva AI",
    company: "Canva",
    logo: "https://logo.clearbit.com/canva.com",
    sentiment: { positive: 77, neutral: 18, negative: 5 },
    mentions: 52400,
    trend: "up",
    trendPercent7d: 10,
    sparklineData: [46, 48, 49, 50, 51, 52, 52],
    type: "tool",
  },
  {
    id: "adobe-firefly",
    rank: 27,
    name: "Adobe Firefly",
    company: "Adobe",
    logo: "https://logo.clearbit.com/adobe.com",
    sentiment: { positive: 75, neutral: 19, negative: 6 },
    mentions: 44600,
    trend: "stable",
    trendPercent7d: 3,
    sparklineData: [43, 43, 44, 44, 44, 45, 45],
    type: "tool",
  },
  {
    id: "pika-labs",
    rank: 28,
    name: "Pika Labs",
    company: "Pika",
    logo: "https://logo.clearbit.com/pika.art",
    sentiment: { positive: 81, neutral: 15, negative: 4 },
    mentions: 28900,
    trend: "up",
    trendPercent7d: 32,
    sparklineData: [20, 22, 24, 26, 27, 28, 29],
    type: "tool",
  },
  {
    id: "suno-ai",
    rank: 29,
    name: "Suno AI",
    company: "Suno",
    logo: "https://logo.clearbit.com/suno.com",
    sentiment: { positive: 82, neutral: 14, negative: 4 },
    mentions: 42600,
    trend: "up",
    trendPercent7d: 35,
    sparklineData: [28, 32, 35, 38, 40, 41, 43],
    type: "tool",
  },
  {
    id: "udio",
    rank: 30,
    name: "Udio",
    company: "Udio",
    logo: "https://logo.clearbit.com/udio.com",
    sentiment: { positive: 80, neutral: 15, negative: 5 },
    mentions: 38400,
    trend: "up",
    trendPercent7d: 28,
    sparklineData: [28, 30, 33, 35, 37, 38, 38],
    type: "tool",
  },
  {
    id: "gamma",
    rank: 31,
    name: "Gamma",
    company: "Gamma",
    logo: "https://logo.clearbit.com/gamma.app",
    sentiment: { positive: 79, neutral: 17, negative: 4 },
    mentions: 32800,
    trend: "up",
    trendPercent7d: 18,
    sparklineData: [26, 28, 29, 30, 31, 32, 33],
    type: "tool",
  },
  {
    id: "beautiful-ai",
    rank: 32,
    name: "Beautiful.ai",
    company: "Beautiful.ai",
    logo: "https://logo.clearbit.com/beautiful.ai",
    sentiment: { positive: 76, neutral: 19, negative: 5 },
    mentions: 18600,
    trend: "stable",
    trendPercent7d: 2,
    sparklineData: [18, 18, 18, 18, 19, 19, 19],
    type: "tool",
  },
  {
    id: "tome",
    rank: 33,
    name: "Tome",
    company: "Tome",
    logo: "https://logo.clearbit.com/tome.app",
    sentiment: { positive: 74, neutral: 20, negative: 6 },
    mentions: 22400,
    trend: "down",
    trendPercent7d: -5,
    sparklineData: [24, 24, 23, 23, 22, 22, 22],
    type: "tool",
  },
  {
    id: "zapier-ai",
    rank: 34,
    name: "Zapier AI",
    company: "Zapier",
    logo: "https://logo.clearbit.com/zapier.com",
    sentiment: { positive: 77, neutral: 18, negative: 5 },
    mentions: 28400,
    trend: "up",
    trendPercent7d: 12,
    sparklineData: [24, 25, 26, 27, 27, 28, 28],
    type: "tool",
  },
  {
    id: "make",
    rank: 35,
    name: "Make",
    company: "Make",
    logo: "https://logo.clearbit.com/make.com",
    sentiment: { positive: 78, neutral: 17, negative: 5 },
    mentions: 32600,
    trend: "up",
    trendPercent7d: 15,
    sparklineData: [26, 28, 29, 30, 31, 32, 33],
    type: "tool",
  },
  {
    id: "n8n",
    rank: 36,
    name: "n8n",
    company: "n8n",
    logo: "https://logo.clearbit.com/n8n.io",
    sentiment: { positive: 81, neutral: 15, negative: 4 },
    mentions: 28900,
    trend: "up",
    trendPercent7d: 22,
    sparklineData: [22, 24, 25, 27, 28, 28, 29],
    type: "tool",
  },
  {
    id: "anthropic-workbench",
    rank: 37,
    name: "Anthropic Workbench",
    company: "Anthropic",
    logo: "https://logo.clearbit.com/anthropic.com",
    sentiment: { positive: 79, neutral: 17, negative: 4 },
    mentions: 18400,
    trend: "up",
    trendPercent7d: 18,
    sparklineData: [14, 15, 16, 17, 17, 18, 18],
    type: "tool",
  },
  {
    id: "langchain",
    rank: 38,
    name: "LangChain",
    company: "LangChain",
    logo: "https://logo.clearbit.com/langchain.com",
    sentiment: { positive: 76, neutral: 18, negative: 6 },
    mentions: 45600,
    trend: "up",
    trendPercent7d: 8,
    sparklineData: [42, 43, 43, 44, 45, 45, 46],
    type: "tool",
  },
  {
    id: "llamaindex",
    rank: 39,
    name: "LlamaIndex",
    company: "LlamaIndex",
    logo: "https://logo.clearbit.com/llamaindex.ai",
    sentiment: { positive: 77, neutral: 18, negative: 5 },
    mentions: 32400,
    trend: "up",
    trendPercent7d: 12,
    sparklineData: [28, 29, 30, 31, 31, 32, 32],
    type: "tool",
  },
  {
    id: "hugging-face",
    rank: 40,
    name: "Hugging Face",
    company: "Hugging Face",
    logo: "https://logo.clearbit.com/huggingface.co",
    sentiment: { positive: 82, neutral: 14, negative: 4 },
    mentions: 68400,
    trend: "up",
    trendPercent7d: 10,
    sparklineData: [62, 63, 65, 66, 67, 68, 68],
    type: "tool",
  },
  {
    id: "aws-bedrock",
    rank: 41,
    name: "AWS Bedrock",
    company: "Amazon",
    logo: "https://logo.clearbit.com/aws.amazon.com",
    sentiment: { positive: 74, neutral: 20, negative: 6 },
    mentions: 38600,
    trend: "up",
    trendPercent7d: 15,
    sparklineData: [32, 33, 35, 36, 37, 38, 39],
    type: "tool",
  },
  {
    id: "azure-openai",
    rank: 42,
    name: "Azure OpenAI",
    company: "Microsoft",
    logo: "https://logo.clearbit.com/azure.microsoft.com",
    sentiment: { positive: 75, neutral: 19, negative: 6 },
    mentions: 42800,
    trend: "up",
    trendPercent7d: 10,
    sparklineData: [38, 39, 40, 41, 42, 42, 43],
    type: "tool",
  },
  {
    id: "google-vertex-ai",
    rank: 43,
    name: "Google Vertex AI",
    company: "Google",
    logo: "https://logo.clearbit.com/cloud.google.com",
    sentiment: { positive: 73, neutral: 21, negative: 6 },
    mentions: 36400,
    trend: "up",
    trendPercent7d: 8,
    sparklineData: [33, 34, 34, 35, 36, 36, 36],
    type: "tool",
  },
  {
    id: "cohere-platform",
    rank: 44,
    name: "Cohere Platform",
    company: "Cohere",
    logo: "https://logo.clearbit.com/cohere.com",
    sentiment: { positive: 74, neutral: 20, negative: 6 },
    mentions: 22600,
    trend: "stable",
    trendPercent7d: 2,
    sparklineData: [22, 22, 22, 22, 22, 23, 23],
    type: "tool",
  },
  {
    id: "pinecone",
    rank: 45,
    name: "Pinecone",
    company: "Pinecone",
    logo: "https://logo.clearbit.com/pinecone.io",
    sentiment: { positive: 78, neutral: 17, negative: 5 },
    mentions: 34200,
    trend: "up",
    trendPercent7d: 12,
    sparklineData: [29, 30, 31, 32, 33, 34, 34],
    type: "tool",
  },
  {
    id: "weaviate",
    rank: 46,
    name: "Weaviate",
    company: "Weaviate",
    logo: "https://logo.clearbit.com/weaviate.io",
    sentiment: { positive: 77, neutral: 18, negative: 5 },
    mentions: 24800,
    trend: "up",
    trendPercent7d: 15,
    sparklineData: [20, 21, 22, 23, 24, 24, 25],
    type: "tool",
  },
  {
    id: "supabase-ai",
    rank: 47,
    name: "Supabase AI",
    company: "Supabase",
    logo: "https://logo.clearbit.com/supabase.com",
    sentiment: { positive: 80, neutral: 16, negative: 4 },
    mentions: 28600,
    trend: "up",
    trendPercent7d: 18,
    sparklineData: [22, 24, 25, 26, 27, 28, 29],
    type: "tool",
  },
  {
    id: "base44",
    rank: 48,
    name: "Base44",
    company: "Base44",
    logo: "https://logo.clearbit.com/base44.com",
    sentiment: { positive: 78, neutral: 18, negative: 4 },
    mentions: 16400,
    trend: "up",
    trendPercent7d: 35,
    sparklineData: [10, 12, 13, 14, 15, 16, 16],
    type: "tool",
  },
  {
    id: "tempo-labs",
    rank: 49,
    name: "Tempo Labs",
    company: "Tempo",
    logo: "https://logo.clearbit.com/tempolabs.ai",
    sentiment: { positive: 81, neutral: 15, negative: 4 },
    mentions: 18900,
    trend: "up",
    trendPercent7d: 42,
    sparklineData: [10, 12, 14, 16, 17, 18, 19],
    type: "tool",
  },
  {
    id: "magic-patterns",
    rank: 50,
    name: "Magic Patterns",
    company: "Magic Patterns",
    logo: "https://logo.clearbit.com/magicpatterns.com",
    sentiment: { positive: 79, neutral: 17, negative: 4 },
    mentions: 14800,
    trend: "up",
    trendPercent7d: 28,
    sparklineData: [10, 11, 12, 13, 14, 14, 15],
    type: "tool",
  },
];

// =============================================================================
// API FUNCTIONS - Update these to use real fetch calls when API is ready
// =============================================================================

/**
 * Fetch all tools/LLMs
 * TODO: Replace with: return fetch(`${BASE_URL}/tools`).then(res => res.json())
 */
export async function fetchTools(): Promise<Tool[]> {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 300));
  return mockTools;
}

/**
 * Fetch tool/LLM details by ID
 * TODO: Replace with: return fetch(`${BASE_URL}/tools/${id}`).then(res => res.json())
 */
export async function fetchToolDetail(id: string): Promise<ToolDetail | null> {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 300));
  
  // Find the tool in the list
  const tool = mockTools.find((t) => t.id === id);
  if (!tool) return null;
  
  // Generate detail object
  return {
    ...tool,
    description: `${tool.name} ist ein führendes ${tool.type === "llm" ? "Sprachmodell" : "AI-Tool"} von ${tool.company}.`,
    versions: tool.type === "llm" ? ["Latest", "Previous"] : ["v2.0", "v1.0"],
    currentVersion: tool.type === "llm" ? "Latest" : "v2.0",
    bestFor: tool.type === "llm" 
      ? ["Konversation", "Code-Generierung", "Textanalyse", "Kreatives Schreiben"]
      : ["Produktivität", "Automatisierung", "Kreativität", "Zusammenarbeit"],
    rating: 4.0 + (tool.sentiment.positive / 100) * 0.9,
    trendData: [
      { date: "Jan", mentions: Math.round(tool.mentions * 0.7), sentiment: tool.sentiment.positive - 5 },
      { date: "Feb", mentions: Math.round(tool.mentions * 0.75), sentiment: tool.sentiment.positive - 4 },
      { date: "Mär", mentions: Math.round(tool.mentions * 0.8), sentiment: tool.sentiment.positive - 3 },
      { date: "Apr", mentions: Math.round(tool.mentions * 0.85), sentiment: tool.sentiment.positive - 2 },
      { date: "Mai", mentions: Math.round(tool.mentions * 0.92), sentiment: tool.sentiment.positive - 1 },
      { date: "Jun", mentions: tool.mentions, sentiment: tool.sentiment.positive },
    ],
    recentMentions: [
      {
        id: "1",
        source: "Twitter",
        text: `${tool.name} wird immer beliebter in der Community.`,
        date: "vor 3 Stunden",
        sentiment: "positive",
      },
      {
        id: "2",
        source: "Reddit",
        text: `Diskussion über ${tool.name} Features und Anwendungsfälle.`,
        date: "vor 1 Tag",
        sentiment: "neutral",
      },
      {
        id: "3",
        source: "Hacker News",
        text: `Vergleich von ${tool.name} mit anderen ${tool.type === "llm" ? "Modellen" : "Tools"}.`,
        date: "vor 2 Tagen",
        sentiment: "positive",
      },
    ],
  };
}
