"""add url_hash to articles

Revision ID: 435b852d9d02
Revises: 001
Create Date: 2026-02-05 12:42:26.001691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435b852d9d02'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('url_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_articles_url_hash'), 'articles', ['url_hash'], unique=False)
    op.drop_index('ix_sentiment_timeseries_entity_timestamp', table_name='sentiment_timeseries')
    op.create_index('ix_sentiment_timeseries_entity_timestamp', 'sentiment_timeseries', ['entity_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentiment_timeseries_entity_timestamp', table_name='sentiment_timeseries', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('ix_sentiment_timeseries_entity_timestamp', 'sentiment_timeseries', ['entity_id', sa.text('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_articles_url_hash'), table_name='articles')
    op.drop_column('articles', 'url_hash')
    # ### end Alembic commands ###
