"""add scheduler_execution_log table

Revision ID: 67a003713f58
Revises: 6d279f8e2869
Create Date: 2026-02-05 12:48:04.359255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a003713f58'
down_revision: Union[str, Sequence[str], None] = '6d279f8e2869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentiment_timeseries_entity_timestamp', table_name='sentiment_timeseries')
    op.create_index('ix_sentiment_timeseries_entity_timestamp', 'sentiment_timeseries', ['entity_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentiment_timeseries_entity_timestamp', table_name='sentiment_timeseries', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('ix_sentiment_timeseries_entity_timestamp', 'sentiment_timeseries', ['entity_id', sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
