"""add reddit_sentiment to sentiment_timeseries

Revision ID: 6d279f8e2869
Revises: 435b852d9d02
Create Date: 2026-02-05 12:42:34.514482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d279f8e2869'
down_revision: Union[str, Sequence[str], None] = '435b852d9d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_timeseries', sa.Column('reddit_sentiment', sa.Float(), nullable=True))
    op.add_column('sentiment_timeseries', sa.Column('reddit_thread_count', sa.Integer(), nullable=True))
    op.drop_index('ix_sentiment_timeseries_entity_timestamp', table_name='sentiment_timeseries')
    op.create_index('ix_sentiment_timeseries_entity_timestamp', 'sentiment_timeseries', ['entity_id', 'timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentiment_timeseries_entity_timestamp', table_name='sentiment_timeseries', postgresql_ops={'timestamp': 'DESC'})
    op.create_index('ix_sentiment_timeseries_entity_timestamp', 'sentiment_timeseries', ['entity_id', sa.text('timestamp DESC')], unique=False)
    op.drop_column('sentiment_timeseries', 'reddit_thread_count')
    op.drop_column('sentiment_timeseries', 'reddit_sentiment')
    # ### end Alembic commands ###
